Task 8 http
OlgaMardvilko/Angular-mentorig-2020 pull request #9
Opened 2020-12-20 18:56 UTC by OlgaMardvilko

2021-01-02 19:11 UTC, aamialkovich requested changes
В лерне помечу как выполненное, но обрати внимание на коммент про редактирование курса)

2021-01-02 19:11 UTC, aamialkovich commented on src/app/models/user.model.ts
> +    this.name.first = user.name.first || null;
Хоть вызов конструктора нигде не вызывается, подозреваю, что здесь будет ошибка, потому что поля name не существует) Так же и в авторах)

2021-01-02 19:11 UTC, aamialkovich commented on src/app/components/courses/course-item/course-item.component.html
>          <p [appBorderColor]="courseItem.creationDate" class="date">
Тут тоже стоило бы поменять))
И везде, где компилятор ругается)

2021-01-02 19:11 UTC, aamialkovich commented on src/app/components/header/user-authorization/user-authorization.component.ts
> +      .subscribe(user => console.log('user', user));
Можно было отобразить информацию о юзере в хедере)

2021-01-02 19:11 UTC, aamialkovich commented on src/app/components/courses/add-course-page/add-course-page.component.ts
> +    const name = this.courseData ? this.courseData.name : '';
В случае редактирования этот метод должен вызываться после того, как данные будут получены с бэкэнда. В теперешней имплементации форма всегда будет пустой)

2021-01-03 10:48 UTC, OlgaMardvilko commented on src/app/components/header/user-authorization/user-authorization.component.ts
> +      .subscribe(user => console.log('user', user));
Hi @aamialkovich. Thanks, this functionality required in Task 9. Will be done.

2021-01-03 10:49 UTC, OlgaMardvilko commented on src/app/components/courses/course-item/course-item.component.html
>          <p [appBorderColor]="courseItem.creationDate" class="date">
Hi @aamialkovich. Fixed in next task. Thanks.

2021-01-03 11:00 UTC, OlgaMardvilko commented on src/app/models/user.model.ts
> +    this.name.first = user.name.first || null;
Hi @aamialkovich. We have property name from user model on server and can see it when get user data. So, I changed previous model and constructor for new valid data. Maybe I misunderstood what you mean. Thanks.

2021-01-08 09:38 UTC, merged